name: Lint Python Code

on:
  push:
    branches: [ "main", "set-up" ]
  pull_request:
    types: [closed]
    branches: ["main"]

jobs:
  lint:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run pylint
        run: |
          find . -name "*.py" | xargs pylint --output-format=colorized || exit 1 